/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DataContract.proto */

#ifndef PROTOBUF_C_DataContract_2eproto__INCLUDED
#define PROTOBUF_C_DataContract_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct DataContracts__Guid DataContracts__Guid;
typedef struct DataContracts__CommandInvokeData DataContracts__CommandInvokeData;
typedef struct DataContracts__CommandInvokeResult DataContracts__CommandInvokeResult;
typedef struct DataContracts__MenuItemData DataContracts__MenuItemData;
typedef struct DataContracts__MenuData DataContracts__MenuData;


/* --- enums --- */

typedef enum _DataContracts__ShellResult {
  DATA_CONTRACTS__SHELL_RESULT__Ok = 0,
  DATA_CONTRACTS__SHELL_RESULT__Error = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DATA_CONTRACTS__SHELL_RESULT)
} DataContracts__ShellResult;

/* --- messages --- */

/*
 * [START data]
 * guid message
 */
struct  DataContracts__Guid
{
  ProtobufCMessage base;
  /*
   * the first 8 bytes of the guid
   */
  protobuf_c_boolean has_lo;
  uint64_t lo;
  /*
   * the second 8 bytes of the guid
   */
  protobuf_c_boolean has_hi;
  uint64_t hi;
};
#define DATA_CONTRACTS__GUID__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_contracts__guid__descriptor) \
    , 0, 0, 0, 0 }


struct  DataContracts__CommandInvokeData
{
  ProtobufCMessage base;
  /*
   *Guid
   */
  DataContracts__Guid *commandid;
  /*
   *List<string>
   */
  size_t n_paths;
  char **paths;
  /*
   *string
   */
  char *extraargs;
};
#define DATA_CONTRACTS__COMMAND_INVOKE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_contracts__command_invoke_data__descriptor) \
    , NULL, 0,NULL, NULL }


struct  DataContracts__CommandInvokeResult
{
  ProtobufCMessage base;
  protobuf_c_boolean has_result;
  DataContracts__ShellResult result;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define DATA_CONTRACTS__COMMAND_INVOKE_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_contracts__command_invoke_result__descriptor) \
    , 0, DATA_CONTRACTS__SHELL_RESULT__Ok, 0, {0,NULL} }


struct  DataContracts__MenuItemData
{
  ProtobufCMessage base;
  char *header;
  DataContracts__Guid *commandid;
  protobuf_c_boolean has_icon;
  ProtobufCBinaryData icon;
  protobuf_c_boolean has_isenabled;
  protobuf_c_boolean isenabled;
  /*
   *List<MenuItemData>
   */
  size_t n_submenuitems;
  DataContracts__MenuItemData **submenuitems;
};
#define DATA_CONTRACTS__MENU_ITEM_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_contracts__menu_item_data__descriptor) \
    , NULL, NULL, 0, {0,NULL}, 0, 0, 0,NULL }


struct  DataContracts__MenuData
{
  ProtobufCMessage base;
  protobuf_c_boolean has_result;
  DataContracts__ShellResult result;
  /*
   *List<MenuItemData>
   */
  size_t n_items;
  DataContracts__MenuItemData **items;
};
#define DATA_CONTRACTS__MENU_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&data_contracts__menu_data__descriptor) \
    , 0, DATA_CONTRACTS__SHELL_RESULT__Ok, 0,NULL }


/* DataContracts__Guid methods */
void   data_contracts__guid__init
                     (DataContracts__Guid         *message);
size_t data_contracts__guid__get_packed_size
                     (const DataContracts__Guid   *message);
size_t data_contracts__guid__pack
                     (const DataContracts__Guid   *message,
                      uint8_t             *out);
size_t data_contracts__guid__pack_to_buffer
                     (const DataContracts__Guid   *message,
                      ProtobufCBuffer     *buffer);
DataContracts__Guid *
       data_contracts__guid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_contracts__guid__free_unpacked
                     (DataContracts__Guid *message,
                      ProtobufCAllocator *allocator);
/* DataContracts__CommandInvokeData methods */
void   data_contracts__command_invoke_data__init
                     (DataContracts__CommandInvokeData         *message);
size_t data_contracts__command_invoke_data__get_packed_size
                     (const DataContracts__CommandInvokeData   *message);
size_t data_contracts__command_invoke_data__pack
                     (const DataContracts__CommandInvokeData   *message,
                      uint8_t             *out);
size_t data_contracts__command_invoke_data__pack_to_buffer
                     (const DataContracts__CommandInvokeData   *message,
                      ProtobufCBuffer     *buffer);
DataContracts__CommandInvokeData *
       data_contracts__command_invoke_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_contracts__command_invoke_data__free_unpacked
                     (DataContracts__CommandInvokeData *message,
                      ProtobufCAllocator *allocator);
/* DataContracts__CommandInvokeResult methods */
void   data_contracts__command_invoke_result__init
                     (DataContracts__CommandInvokeResult         *message);
size_t data_contracts__command_invoke_result__get_packed_size
                     (const DataContracts__CommandInvokeResult   *message);
size_t data_contracts__command_invoke_result__pack
                     (const DataContracts__CommandInvokeResult   *message,
                      uint8_t             *out);
size_t data_contracts__command_invoke_result__pack_to_buffer
                     (const DataContracts__CommandInvokeResult   *message,
                      ProtobufCBuffer     *buffer);
DataContracts__CommandInvokeResult *
       data_contracts__command_invoke_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_contracts__command_invoke_result__free_unpacked
                     (DataContracts__CommandInvokeResult *message,
                      ProtobufCAllocator *allocator);
/* DataContracts__MenuItemData methods */
void   data_contracts__menu_item_data__init
                     (DataContracts__MenuItemData         *message);
size_t data_contracts__menu_item_data__get_packed_size
                     (const DataContracts__MenuItemData   *message);
size_t data_contracts__menu_item_data__pack
                     (const DataContracts__MenuItemData   *message,
                      uint8_t             *out);
size_t data_contracts__menu_item_data__pack_to_buffer
                     (const DataContracts__MenuItemData   *message,
                      ProtobufCBuffer     *buffer);
DataContracts__MenuItemData *
       data_contracts__menu_item_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_contracts__menu_item_data__free_unpacked
                     (DataContracts__MenuItemData *message,
                      ProtobufCAllocator *allocator);
/* DataContracts__MenuData methods */
void   data_contracts__menu_data__init
                     (DataContracts__MenuData         *message);
size_t data_contracts__menu_data__get_packed_size
                     (const DataContracts__MenuData   *message);
size_t data_contracts__menu_data__pack
                     (const DataContracts__MenuData   *message,
                      uint8_t             *out);
size_t data_contracts__menu_data__pack_to_buffer
                     (const DataContracts__MenuData   *message,
                      ProtobufCBuffer     *buffer);
DataContracts__MenuData *
       data_contracts__menu_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   data_contracts__menu_data__free_unpacked
                     (DataContracts__MenuData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*DataContracts__Guid_Closure)
                 (const DataContracts__Guid *message,
                  void *closure_data);
typedef void (*DataContracts__CommandInvokeData_Closure)
                 (const DataContracts__CommandInvokeData *message,
                  void *closure_data);
typedef void (*DataContracts__CommandInvokeResult_Closure)
                 (const DataContracts__CommandInvokeResult *message,
                  void *closure_data);
typedef void (*DataContracts__MenuItemData_Closure)
                 (const DataContracts__MenuItemData *message,
                  void *closure_data);
typedef void (*DataContracts__MenuData_Closure)
                 (const DataContracts__MenuData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    data_contracts__shell_result__descriptor;
extern const ProtobufCMessageDescriptor data_contracts__guid__descriptor;
extern const ProtobufCMessageDescriptor data_contracts__command_invoke_data__descriptor;
extern const ProtobufCMessageDescriptor data_contracts__command_invoke_result__descriptor;
extern const ProtobufCMessageDescriptor data_contracts__menu_item_data__descriptor;
extern const ProtobufCMessageDescriptor data_contracts__menu_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_DataContract_2eproto__INCLUDED */
