/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: DataContract.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "DataContract.pb-c.h"
void   data_contracts__guid__init
                     (DataContracts__Guid         *message)
{
  static const DataContracts__Guid init_value = DATA_CONTRACTS__GUID__INIT;
  *message = init_value;
}
size_t data_contracts__guid__get_packed_size
                     (const DataContracts__Guid *message)
{
  assert(message->base.descriptor == &data_contracts__guid__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_contracts__guid__pack
                     (const DataContracts__Guid *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_contracts__guid__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_contracts__guid__pack_to_buffer
                     (const DataContracts__Guid *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_contracts__guid__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataContracts__Guid *
       data_contracts__guid__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataContracts__Guid *)
     protobuf_c_message_unpack (&data_contracts__guid__descriptor,
                                allocator, len, data);
}
void   data_contracts__guid__free_unpacked
                     (DataContracts__Guid *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_contracts__guid__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_contracts__command_invoke_data__init
                     (DataContracts__CommandInvokeData         *message)
{
  static const DataContracts__CommandInvokeData init_value = DATA_CONTRACTS__COMMAND_INVOKE_DATA__INIT;
  *message = init_value;
}
size_t data_contracts__command_invoke_data__get_packed_size
                     (const DataContracts__CommandInvokeData *message)
{
  assert(message->base.descriptor == &data_contracts__command_invoke_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_contracts__command_invoke_data__pack
                     (const DataContracts__CommandInvokeData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_contracts__command_invoke_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_contracts__command_invoke_data__pack_to_buffer
                     (const DataContracts__CommandInvokeData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_contracts__command_invoke_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataContracts__CommandInvokeData *
       data_contracts__command_invoke_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataContracts__CommandInvokeData *)
     protobuf_c_message_unpack (&data_contracts__command_invoke_data__descriptor,
                                allocator, len, data);
}
void   data_contracts__command_invoke_data__free_unpacked
                     (DataContracts__CommandInvokeData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_contracts__command_invoke_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_contracts__command_invoke_result__init
                     (DataContracts__CommandInvokeResult         *message)
{
  static const DataContracts__CommandInvokeResult init_value = DATA_CONTRACTS__COMMAND_INVOKE_RESULT__INIT;
  *message = init_value;
}
size_t data_contracts__command_invoke_result__get_packed_size
                     (const DataContracts__CommandInvokeResult *message)
{
  assert(message->base.descriptor == &data_contracts__command_invoke_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_contracts__command_invoke_result__pack
                     (const DataContracts__CommandInvokeResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_contracts__command_invoke_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_contracts__command_invoke_result__pack_to_buffer
                     (const DataContracts__CommandInvokeResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_contracts__command_invoke_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataContracts__CommandInvokeResult *
       data_contracts__command_invoke_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataContracts__CommandInvokeResult *)
     protobuf_c_message_unpack (&data_contracts__command_invoke_result__descriptor,
                                allocator, len, data);
}
void   data_contracts__command_invoke_result__free_unpacked
                     (DataContracts__CommandInvokeResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_contracts__command_invoke_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_contracts__menu_item_data__init
                     (DataContracts__MenuItemData         *message)
{
  static const DataContracts__MenuItemData init_value = DATA_CONTRACTS__MENU_ITEM_DATA__INIT;
  *message = init_value;
}
size_t data_contracts__menu_item_data__get_packed_size
                     (const DataContracts__MenuItemData *message)
{
  assert(message->base.descriptor == &data_contracts__menu_item_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_contracts__menu_item_data__pack
                     (const DataContracts__MenuItemData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_contracts__menu_item_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_contracts__menu_item_data__pack_to_buffer
                     (const DataContracts__MenuItemData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_contracts__menu_item_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataContracts__MenuItemData *
       data_contracts__menu_item_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataContracts__MenuItemData *)
     protobuf_c_message_unpack (&data_contracts__menu_item_data__descriptor,
                                allocator, len, data);
}
void   data_contracts__menu_item_data__free_unpacked
                     (DataContracts__MenuItemData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_contracts__menu_item_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   data_contracts__menu_data__init
                     (DataContracts__MenuData         *message)
{
  static const DataContracts__MenuData init_value = DATA_CONTRACTS__MENU_DATA__INIT;
  *message = init_value;
}
size_t data_contracts__menu_data__get_packed_size
                     (const DataContracts__MenuData *message)
{
  assert(message->base.descriptor == &data_contracts__menu_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t data_contracts__menu_data__pack
                     (const DataContracts__MenuData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &data_contracts__menu_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t data_contracts__menu_data__pack_to_buffer
                     (const DataContracts__MenuData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &data_contracts__menu_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DataContracts__MenuData *
       data_contracts__menu_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DataContracts__MenuData *)
     protobuf_c_message_unpack (&data_contracts__menu_data__descriptor,
                                allocator, len, data);
}
void   data_contracts__menu_data__free_unpacked
                     (DataContracts__MenuData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &data_contracts__menu_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor data_contracts__guid__field_descriptors[2] =
{
  {
    "lo",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DataContracts__Guid, has_lo),
    offsetof(DataContracts__Guid, lo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hi",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED64,
    offsetof(DataContracts__Guid, has_hi),
    offsetof(DataContracts__Guid, hi),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_contracts__guid__field_indices_by_name[] = {
  1,   /* field[1] = hi */
  0,   /* field[0] = lo */
};
static const ProtobufCIntRange data_contracts__guid__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor data_contracts__guid__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataContracts.guid",
  "Guid",
  "DataContracts__Guid",
  "DataContracts",
  sizeof(DataContracts__Guid),
  2,
  data_contracts__guid__field_descriptors,
  data_contracts__guid__field_indices_by_name,
  1,  data_contracts__guid__number_ranges,
  (ProtobufCMessageInit) data_contracts__guid__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_contracts__command_invoke_data__field_descriptors[3] =
{
  {
    "commandId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DataContracts__CommandInvokeData, commandid),
    &data_contracts__guid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "paths",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DataContracts__CommandInvokeData, n_paths),
    offsetof(DataContracts__CommandInvokeData, paths),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "extraArgs",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DataContracts__CommandInvokeData, extraargs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_contracts__command_invoke_data__field_indices_by_name[] = {
  0,   /* field[0] = commandId */
  2,   /* field[2] = extraArgs */
  1,   /* field[1] = paths */
};
static const ProtobufCIntRange data_contracts__command_invoke_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor data_contracts__command_invoke_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataContracts.CommandInvokeData",
  "CommandInvokeData",
  "DataContracts__CommandInvokeData",
  "DataContracts",
  sizeof(DataContracts__CommandInvokeData),
  3,
  data_contracts__command_invoke_data__field_descriptors,
  data_contracts__command_invoke_data__field_indices_by_name,
  1,  data_contracts__command_invoke_data__number_ranges,
  (ProtobufCMessageInit) data_contracts__command_invoke_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_contracts__command_invoke_result__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DataContracts__CommandInvokeResult, has_result),
    offsetof(DataContracts__CommandInvokeResult, result),
    &data_contracts__shell_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(DataContracts__CommandInvokeResult, has_data),
    offsetof(DataContracts__CommandInvokeResult, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_contracts__command_invoke_result__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange data_contracts__command_invoke_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor data_contracts__command_invoke_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataContracts.CommandInvokeResult",
  "CommandInvokeResult",
  "DataContracts__CommandInvokeResult",
  "DataContracts",
  sizeof(DataContracts__CommandInvokeResult),
  2,
  data_contracts__command_invoke_result__field_descriptors,
  data_contracts__command_invoke_result__field_indices_by_name,
  1,  data_contracts__command_invoke_result__number_ranges,
  (ProtobufCMessageInit) data_contracts__command_invoke_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_contracts__menu_item_data__field_descriptors[5] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DataContracts__MenuItemData, header),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commandId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DataContracts__MenuItemData, commandid),
    &data_contracts__guid__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icon",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(DataContracts__MenuItemData, has_icon),
    offsetof(DataContracts__MenuItemData, icon),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "isEnabled",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DataContracts__MenuItemData, has_isenabled),
    offsetof(DataContracts__MenuItemData, isenabled),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "subMenuItems",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DataContracts__MenuItemData, n_submenuitems),
    offsetof(DataContracts__MenuItemData, submenuitems),
    &data_contracts__menu_item_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_contracts__menu_item_data__field_indices_by_name[] = {
  1,   /* field[1] = commandId */
  0,   /* field[0] = header */
  2,   /* field[2] = icon */
  3,   /* field[3] = isEnabled */
  4,   /* field[4] = subMenuItems */
};
static const ProtobufCIntRange data_contracts__menu_item_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor data_contracts__menu_item_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataContracts.MenuItemData",
  "MenuItemData",
  "DataContracts__MenuItemData",
  "DataContracts",
  sizeof(DataContracts__MenuItemData),
  5,
  data_contracts__menu_item_data__field_descriptors,
  data_contracts__menu_item_data__field_indices_by_name,
  1,  data_contracts__menu_item_data__number_ranges,
  (ProtobufCMessageInit) data_contracts__menu_item_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor data_contracts__menu_data__field_descriptors[2] =
{
  {
    "result",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DataContracts__MenuData, has_result),
    offsetof(DataContracts__MenuData, result),
    &data_contracts__shell_result__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "items",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DataContracts__MenuData, n_items),
    offsetof(DataContracts__MenuData, items),
    &data_contracts__menu_item_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned data_contracts__menu_data__field_indices_by_name[] = {
  1,   /* field[1] = items */
  0,   /* field[0] = result */
};
static const ProtobufCIntRange data_contracts__menu_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor data_contracts__menu_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "DataContracts.MenuData",
  "MenuData",
  "DataContracts__MenuData",
  "DataContracts",
  sizeof(DataContracts__MenuData),
  2,
  data_contracts__menu_data__field_descriptors,
  data_contracts__menu_data__field_indices_by_name,
  1,  data_contracts__menu_data__number_ranges,
  (ProtobufCMessageInit) data_contracts__menu_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue data_contracts__shell_result__enum_values_by_number[2] =
{
  { "Ok", "DATA_CONTRACTS__SHELL_RESULT__Ok", 0 },
  { "Error", "DATA_CONTRACTS__SHELL_RESULT__Error", 1 },
};
static const ProtobufCIntRange data_contracts__shell_result__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex data_contracts__shell_result__enum_values_by_name[2] =
{
  { "Error", 1 },
  { "Ok", 0 },
};
const ProtobufCEnumDescriptor data_contracts__shell_result__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "DataContracts.ShellResult",
  "ShellResult",
  "DataContracts__ShellResult",
  "DataContracts",
  2,
  data_contracts__shell_result__enum_values_by_number,
  2,
  data_contracts__shell_result__enum_values_by_name,
  1,
  data_contracts__shell_result__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
